#!/bin/bash

REF="$1"
REMOTE="$2"

r10kconf="$(mktemp)"
trap "rm -f ${r10kconf}" 0 1 2 3 13 15

cat << EOF > $r10kconf
# The location to use for storing cached Git repos
:cachedir: '/etc/puppetlabs/code/cache'

# A list of git repositories to create
:sources:
  :main:
    remote: '${REMOTE}'
    basedir: '/etc/puppetlabs/code/environments'
EOF

if [[ $REF =~ 'refs/heads/' ]]; then
  branch=$(cut -d/ -f3 <<<"${REF}")
  /usr/local/bin/g10k -config "$r10kconf" -branch "$branch"
  if [ -x ${HOME}/notify ]; then
     echo "Sending notification with ${HOME}/notify"
     ${HOME}/notify $? ${branch} ${REMOTE}
  fi
else
  echo "g10k skipping $REF"
fi
