#!/bin/bash

REF="$1"
REMOTE="$2"

r10kconf="$(mktemp)"
trap "rm -f ${r10kconf}" 0 1 2 3 13 15

cat << EOF > $r10kconf
# The location to use for storing cached Git repos
:cachedir: '/etc/puppetlabs/code/cache'

# A list of git repositories to create
:sources:
  :main:
    remote: '${REMOTE}'
    basedir: '/etc/puppetlabs/code/environments'
EOF

if [[ $REF =~ 'refs/heads/' ]]; then
  branch=$(cut -d/ -f3 <<<"${REF}")
  /usr/local/bin/g10k -config "$r10kconf" -branch "$branch"
  rc=$?
  if [ -f ./.apprise.yml -a -x /usr/bin/apprise ]; then
     echo "Sending notification with apprise ${rc} ${branch} ${REMOTE}'"
     if [ ${rc} -eq 0 ]; then
	 title="G10K SUCCESS"
     else
	 title="G10 FAILED: ${rc}"
     fi
     /usr/bin/apprise --config ${PWD}/.apprise.yml --title "${title}" --body "Branch: ${branch}"
  elif [ -x ./notify ]; then
     echo "Sending notification with '${PWD}/notify ${rc} ${branch} ${REMOTE}'"
     ./notify ${rc} ${branch} ${REMOTE}
  fi
else
  echo "g10k skipping $REF"
fi
