#!/usr/bin/with-contenv bash

# load env file if it exists
if [ -f "/config/env" ]; then
    source /config/env
    print_vars "After sourcing /config/env"
fi

# make our config dirs
for dir in cache environments modules; do
    test -e /etc/puppetlabs/code/${dir} || mkdir -p /etc/puppetlabs/code/${dir}
    chown -R abc.abc /etc/puppetlabs/code/${dir}
    chmod ug+rwX,o+rX /etc/puppetlabs/code/${dir}
done

date
