#!/usr/bin/with-contenv bash

print_vars () {
    if [ -n "${1}" ]; then
	title=" ${1}"
    else
	title=""
    fi
    echo "Environment${title}:"
    echo "    PUID=${PUID}"
    echo "    PGID=${PGID}"
    echo "    TZ=${TZ}"
}

print_vars 

# load env file if it exists
if [ -f "/config/env" ]; then
    source /config/env
    print_vars "After sourcing /config/env"
fi

# Link /config/.ssh into our home dir
if [ -f "/config/.ssh" -a "$(readlink -f /home/abc/.ssh)" != "/config/.ssh" ]; then
    test -e /home/abc/.ssh && rm -rf /home/abc/.ssh
    ln -s /config/.ssh /home/abc/.ssh
    chown -R ${PUID}:${PGID} /config/.ssh
fi

# make our config dirs
for dir in cache; do
    mkdir -p /etc/puppetlabs/code/${dir}
    chown -R ${PUID}:${PGID} /etc/puppetlabs/code/${dir}
done
